<div style="background-image: url(foto.png);background-repeat: no-repeat; background-size: 950px 65px;">
<b>
<br>
<font size="5"><p style="text-align: center;">Introdução à Programação de Computadores</p></font>
</b>
<br>
<font size="4"><b>Professores:</b> <br> Jefersson A. dos Santos - jefersson@dcc.ufmg.br
<br>
<font size="4">João Guilherme Maia de Menezes - jgmm@dcc.ufmg.br
</font>
<font size="3">

</font>
</div>

# Capítulo 11 - Biblioteca Científicas: numpy e matplotlib

# 1. Introdução
---------------
Nesta aula prática, estamos usando o Jupyter Notebook, que é um ambiente computacional interativo, no qual você poderá combinar execução de código, formatação de textos, matemática, gráficos e mídia. 
Para maiores informações consulte o link: [jupyter.org](https://jupyter.org/ "Página jupyter.org")

**numpy e matplotlib** 

Hoje serão abordados dois pacotes do Python: o Numpy e o Matplotlib.

Um pacote pode ser compreendido como uma biblioteca que fornece funcionalidades específicas e que, desta forma, permite estender o núcleo básico do Python.

O **numpy**, por exemplo, é o pacote fundamental para computação científica do Python. A instalação básica do Python não inclui o Numpy (ele deve ser instalado separadamente). 

Já o **matplotlib** é um pacote (biblioteca) para plotar/desenhar gráficos no Python. Existem outros pacotes com a mesma finalidade, e o Matplotlib foi o escolhido para o curso, pois é um dos mais usados. Assim como o numpy, o matplotlib também não é instalado com a versão básica do Python (ele deve ser instalado separadamente).

A instalação do Anaconda, que foi recomendada para este curso, inclui o Python e uma série de pacotes científicos, dentre eles o numpy e o matplotlib.

Para ter uma noção dos pacotes instalados pelo Anaconda, execute no Prompt do Comando (do Anaconda) o comando:
*conda list*

Alternativamente, execute a célula abaixo:

In [0]:
print(help("modules"))


Please wait a moment while I gather a list of all available modules...



/usr/local/lib/python3.6/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)


<IPython.core.display.Javascript object>

/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning:

The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning:

The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).

Using TensorFlow backend.


INFO:summarizer.preprocessing.cleaner:'pattern' package not found; tag filters are not available for English


The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning:

sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.



/usr/lib/python3.6/pkgutil.py:92: UserWarning:

The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them

/usr/local/lib/python3.6/dist-packages/nltk/twitter/__init__.py:20: UserWarning:

The twython library has not been installed. Some functionality from the twitter package will not be available.

Exception ignored in: <_io.FileIO name='/usr/local/lib/python3.6/dist-packages/theano/gof/c_code/lazylinker_c.c' mode='rb' closefd=True>



Nas próximas seções faremos uma introdução ao numpy.

Antes de prosseguir, no entanto, é importante relembrar alguns conceitos importantes das listas.

**1.1 Listas**

Uma lista (**list**) é o equivalente do Python para um array, sendo que pode ser redimensionado e pode conter elementos de tipos diferentes.

Execute o código abaixo e preste atenção aos comentários de cada linha e a saída que ela gera.

In [0]:
#listas - relembrando algumas propriedades
xs = [3, 1, 2]       # Cria uma lista
print(xs, xs[2])     # Imprime "[3, 1, 2] 2"
print(xs[-1])        # Indices negativos contam a partir do final da lista: imprime "2"
xs[2] = 'minas'      # Listas podem conter elementos de tipos diferentes
print(xs)            # Imprime "[3, 1, 'minas']"
xs.append('gerais')  # Adiciona novo elemento ao fim da lista
print(xs)            # Imprime  "[3, 1, 'minas', 'gerais']"
x = xs.pop()         # Remove e retorna o último elemento da lista
print(x, xs)         # Imprime "gerais [3, 1, 'minas']"


**Fatiamento de listas**: além de poder acessar um elemento de cada vez, o Python possui uma notação concisa para permitir o acesso a sublistas, que é conhecida como fatiamento (*slicing*).


In [0]:
nums = list(range(5))     # range is a função pré-definida que cria uma lista de inteiros
print(nums)               # imprime "[0, 1, 2, 3, 4]"
print(nums[2:4])          # obtém uma fatia do índice 2 ao 4 (**exclusive**); imprime "[2, 3]"
print(nums[2:])           # obtém uma fatia do índice 2 até o final; imprime "[2, 3, 4]"
print(nums[:2])           # obtém uma fatia do início até o índice 2 (exclusive); imprime "[0, 1]"
print(nums[:])            # obtém uma fatia da lista toda; imprime "[0, 1, 2, 3, 4]"
print(nums[:-1])          # indices do fatiamento podem ser negativos; imprime "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # atribui uma nova sublista à fatia
print(nums)               # imprime "[0, 1, 8, 9, 4]"


**Exercício 1**

Dada a lista abaixo:
```python
lista1 = [0, 1, 2, 3, 2, 1, 0]
```
determine o fatiamento que produza a lista [2, 3, 2] e imprima

In [0]:
#Exercício 1 - faça sua reposta nessa célula

lista1 = [0, 1, 2, 3, 2, 1, 0]

# crie o código aqui


Uma questão interessante sobre as listas (que também vale para dicionários e alguns objetos do Python) é que quando você atribui uma lista a outra, as duas passam a *apontar* para os mesmos valores.

Verifique com atenção os comentários do código abaixo:


In [0]:
lista1 = [1, 2, 3, 4]
print(lista1)         # vai imprimir [1, 2, 3, 4]

lista2 = lista1       # essa atribuição faz com que lista2 aponte para os mesmos valores de lista1
                      # dessa forma, qualquer alteração em lista2 será refletida em lista1
                
print(lista2)         # vai imprimir [1, 2, 3, 4]

lista2.append(10)     # adiciona 10 ao último elemento da lista

print(lista2)         # vai imprimir [1, 2, 3, 4, 10]
print(lista1)         # vai imprimir [1, 2, 3, 4, 10]

# para evitar esse comportamento, a atriuição deve ser feita com a função list()
lista1 = [1, 2, 3, 4]
print(lista1)         # vai imprimir [1, 2, 3, 4]
lista2 = list(lista1) # nesse caso, uma copia dos valores de lista1 é criada separadamente para lista2
print(lista2)         # vai imprimir [1, 2, 3, 4]

lista2.append(10)     # adiciona 10 ao último elemento da lista

print(lista2)         # vai imprimir [1, 2, 3, 4, 10]
print(lista1)         # vai imprimir [1, 2, 3, 4]



# 2. Numpy
---------------

O [Numpy](http://www.numpy.org/) é a principal biblioteca de computação científica do Python.
Ela fornece um objeto de array multidimensional de alta performance, bem como ferramentas para trabalhar com esses arrays.

Um array do numpy é um grid (grade) de valores, **todos do mesmo tipo**, e é indexado por uma tupla de inteiros não negativos.

O número de dimensões é o *rank* do array.

O *shape* (formato) de um array é uma tupla de inteiros indicando o tamanho do array em cada dimensão.

O código da célula abaixo ilustra esses conceitos e fornece exemplos de inicialização de arrays do numpy.

**Clique na célula e execute o código (CTRL+ENTER)**. Altere os valores e analise os resultados.

In [0]:
# numpy código 1

"""
 O import permite que o nosso programa utilize um pacote.
 No comando abaixo, fazemos o import do numpy e chamaremos 
 ele de np no nosso programa
"""

import numpy as np

a = np.array([1, 2, 3])   # cria um array de rank 1 (um vetor)

print("\nArray rank 1:")
print(a)                  # imprime "[1, 2, 3]"
print("\nTipo:")
print(type(a))            # imprime "<class 'numpy.ndarray'>"
print("\nShape:")
print(a.shape)            # imprime "(3,)"
a[0] = 5                  # muda um elemento do array 
print("\nElementos:")
print(a[0], a[1], a[2])   # imprime "5 2 3"

b = np.array([[1,2,3],[4,5,6]])    # cria um array de rank 2 (uma matriz)
print("\nArray rank 2:")
print(b)
print("\nShape:")
print(b.shape)                     # imprime "(2, 3)"
print("\nAlguns elementos:")
print(b[0, 0], b[0, 1], b[1, 0])   # imprime "1 2 4"



Você pode especificar o tipo de dado do array na sua criação, usando o parâmetro dtype), veja exemplos a seguir:


In [0]:
# numpy código 2

import numpy as np
print("\nfloat64:")
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(x)
print("\nint64:")
y = np.array([[1,2],[3,4]], dtype=np.int64)
print(y)
print("\nint32:")
z = np.array([[1,2],[3,4]], dtype=np.int32)
print(z)

**Exercício 2**

a) Crie um array do numpy com 3 linhas e 2 colunas (cmo valores que você escolher)

b) Imprima o array

c) Imprima o formato (shape) do array

d) Imprima o rank do array
 
e) Imprima o primeiro elemento da primeira linha e o último elemento da última linha


In [0]:
# Exercício 2 - faça sua resposta nessa célula

# a) Crie um array do numpy com 3 linhas e 2 colunas (cmo valores que você escolher)


# b) Imprima o array


# c) Imprima o formato (shape) do array


# d) Imprima o rank do array


# e) Imprima o primeiro elemento da primeira linha e o último elemento da última linha




 
 
O Numpy também fornece funções para criação de arrays:


In [0]:
# numpy código 3

import numpy as np

a = np.zeros((2,2))   # cria um array de 2 linhas e 2 duas colunas
                      # e inicializa todos elementos com valor zero

print(a)              # imprime "[[ 0.  0.]
                      #           [ 0.  0.]]"
print("--------------------------------------------")
b = np.ones((1,2))    # cria um array de 1 linha e 2 duas colunas
                      # e inicializa todos elementos com valor 1.0
print(b)              # imprime "[[ 1.  1.]]"
print("--print(a)------------------------------------------")
c = np.full((2,2), 7)  # cria um array de 2 linhas e 2 duas colunas
                       # e inicializa todos elementos com a constante 7.
print(c)               # imprime  "[[ 7.  7.]
                       #            [ 7.  7.]]"
print("--------------------------------------------")
d = np.eye(2)         # cria uma matriz identidade de 2 linhas e 2 duas colunas
print(d)              # imprime "[[ 1.  0.]
                      #           [ 0.  1.]]"
print("--------------------------------------------")
e = np.random.random((2,3))  # cria um array de 2 linhas e 3 colunas com valores randômicos
print(e)                     # imprime algo como "[[ 0.50850175  0.56783854  0.66564824]
                             #                     [ 0.91887667  0.45616976  0.08625947]]


Por fim, também é possível criar um array vazio e acrescentar as linhas *programaticamente*, mas a sintaxe é bem diferente das listas porque os arrays podem ter muitas dimensões:

In [0]:
# numpy código 4

# Cria um array de rank 1 vazio e acrescenta elementos

print("Vetor:")
vetor = np.empty((0), dtype=np.float64)
print("Acrescenta um elemento:")
vetor = np.append(vetor, [0.])
print(vetor)
print("Acrescenta vários elementos de uma vez:")
vetor = np.append(vetor, [1., 2., 3.])
print(vetor)


# Cria um array de rank 2 vazio e acrescenta linhas
print("\nMatriz:")
matriz = np.empty((0, 3), dtype=np.float64)
print("Acrescenta uma linha:")
matriz = np.append(matriz, [[0., 1., 2.]], axis=0)
print(matriz)
print("Acrescenta várias linhas de uma vez:")
matriz = np.append(matriz, [[3., 4., 5.], [6., 7., 8.], [9., 10., 11.]], axis=0)
print(matriz)



**2.1 Indexação de Arrays (acesso aos elementos do array)**

O Numpy oferece vários modos de acessar os elementos do array.

**Fatiamento**: de modo semelhante às listas do Python, os arrays do numpy podem ser fatiados. Como os arrays do numpy podem ser multidimensionais, você precisa especificar *a fatia* de cada dimensão do array:


In [0]:
# numpy código 5

import numpy as np

# cria o seguinte array com shape(3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# usa fatiamento para obter o subarray com os elementos 
# das primeiras 2 linhas e das colunas 1 e 2.
# o subarray é atribuído a slice_de_a
# [[2 3]
#  [6 7]]
slice_de_a = a[:2, 1:3]
print("\nslice_de_a")
print(slice_de_a)
print("")

# Uma fatia de um array é uma visão dos mesmos dados, então as 
# modificações são refletidas no array original.
print(a[0, 1])         # imprime "2"
slice_de_a[0, 0] = 77  # slice_de_a[0, 0] é o mesmo dado de a[0, 1]
print("\nslice_de_a")
print(slice_de_a)
print("")
print(a[0, 1])         # imprime "77"

# esse comportamento é desejável em muitas situações
# se fosse necessário criar uma cópia independente, poderia ser
# utilizado o construtor np.array(), conforme exemplo abaixo:
novo_array = np.array(a[:2, 1:3])
print(a[0, 1])         # imprime "77"
novo_array[0, 0] = 81  # slice_de_a[0, 0] é o mesmo dado de a[0, 1]
print("\nnovo_array")
print(novo_array)
print("")
print(a[0, 1])         # imprime "77"


**Exercício 3**

Dado um array ar, de 5 linhas e 4 colunas:<br>
[[0, 0, 0, 0],<br>
 [0, 0, 0, 0],<br>
 [0, 1, 2, 0],<br>
 [0, 3, 4, 0],<br>
 [0, 0, 0, 0]]

Faça um fatiamento que produza o subarray:<br>
[[1, 2],<br>
 [3, 4]]

In [0]:
# Exercício 3 - faça sua resposta nessa célula

import numpy as np

ar = np.array([[0, 0, 0, 0],
               [0, 0, 0, 0],
               [0, 1, 2, 0],
               [0, 3, 4, 0],
               [0, 0, 0, 0]])

# crie o seu código aqui



**Indexação inteira com fatiamento**: você também pode usar indexação inteira com fatiamento, mas o subarray produzido terá rank menor que o original.

In [0]:
!# numpy código 6

import numpy as np

# cria o seguinte array com shape(3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
linha_r1 = a[1, :]    # visão da 2a linha (com Rank 1)
linha_r2 = a[1:2, :]  # visão da 2a linha (com Rank 2)
print(linha_r1, linha_r1.shape)  # imprime "[5 6 7 8] (4,)"
print(linha_r2, linha_r2.shape)  # imprime "[[5 6 7 8]] (1, 4)"

# podemos fazer a mesma coisa com colunas
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # imprime "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # imprime "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"



**Indexação boleana**: você também pode usar indexação com base no valor dos elementos da matriz.

No exemplo abaixo, vamos zerar* todos os elementos negativos da matriz.



In [0]:
# numpy código 7

import numpy as np

a = np.array([[21,-6], [43, 14], [-5, 36]])

print ("Array original:")
print(a)

a[a<0] = 0

print ("Depois da alteração:")
print(a)



**2.2 Operações matemáticas**

Operações matemáticas básicas operam elemento a elemento nos arrays.
Essas operações podem ser feitas usando os operadores (+, -, \*, etc) ou através de funções (np.add(), np.subtract(), np.multiply(), etc)

**Arrays e constantes**: as operações mais simples são com constantes, onde é possível, por exemplo, somar uma constante a todos elementos do array ou multiplicar todos os elementos por uma constante.


In [0]:
# numpy código 8

#operações com constantes

x = np.array([[1,2],[3,4]])
print("Array x:")
print(x)
y = x + 10
print("Array y (x + 10):")
print(y)
x = x*10
print("Array x multiplicado por 10:")
print(x)


**Operações com arrays**: essas operações envolvem dois ou mais arrays.

In [0]:
# numpy código 9

#operações com arrays

import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# soma elemento a elemento; ambas produzem o array:
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# subtração elemento a elemento; ambas produzem o array:
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# multiplicação elemento a elemento (diferente da multiplicação de matrizes)
# ambos produzem o array:
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# divisão elemento a elemento; ambas produzem o array:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# raiz quadrada elemento a elemento
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))




O Numpy fornece uma função específica para a multiplicação de matrizes, que é a função **dot**:

In [0]:
# numpy código 10

import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Produto interno de vetores, ambos produzem 219
print(v.dot(w))
print(np.dot(v, w))

# Produto de Matrix / vetor; ambos produzem o array de rank 1 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Produto de Matrix / matrix; ambos produzem o array de rank 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))



O Numpy fornece várias funções para realizar computações em arrays, uma das mais úteis é a função **sum**:

In [0]:
# numpy código 11

import numpy as np

x = np.array([[1,2, 3, 4],[10, 20, 30, 40]], dtype=np.int64)

print("Array:")
print(x)

print("Soma de todos elementos de x: ")
print(np.sum(x))  
print("Soma dos elementos de cada coluna:")
print(np.sum(x, axis=0))
print("Soma dos elementos de cada linha:")
print(np.sum(x, axis=1)) 


**Exercício 4**

    
a) Crie um array do numpy, com duas linhas e 5 colunas com valores float (não esqueça de usar o parâmetro **dtype**) de sua escolha.

E imprima:

b) a soma dos elementos das linhas do array

c) a multiplicação dos elementos das colunas do array

d) a média de todos elementos do array

e) a média dos elementos das linhas do array

f) a média dos elementos das colunas do array

g) o desvio padrão de todos elementos do array

h) o desvio padrão das linhas do array

i) o desvio padrão dos elementos das colunas do array

**Obs.: para o desvio padrão, utilize a função *std***.

Para verificar uma lista de funções úteis ofrnecidas pelo numpy, [consulte a documentação](http://docs.scipy.org/doc/numpy/reference/routines.math.html).



In [28]:
# Exercício 4 - faça sua resposta nessa célula

import numpy as np
 
# a) Crie um array do numpy, com duas linhas e 5 colunas com valores 
#    float (não esqueça de usar o parâmetro **dtype**) de sua escolha.

array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=np.float64)
print('Array:\n', array)

# b) a soma dos elementos das linhas do array

soma = np.sum(array, axis=1, keepdims=True)
print('Soma dos elementos das linhas do array:\n', soma)

# c) a multiplicação dos elementos das colunas do array

mult = np.prod(array, axis=0, keepdims=True)
print('Multiplicação dos elementos das colunas do array:\n', mult)


# d) a média de todos elementos do array

media = np.mean(array)
print('Média de todos elementos do array:\n', media)


# e) a média dos elementos das linhas do array

media_linha = np.mean(array, axis=1, keepdims=True)
print('Média dos elementos das linhas do array:\n', media_linha)


# f) a média dos elementos das colunas do array

media_coluna = np.mean(array, axis=0, keepdims=True)
print('Média dos elementos das colunas do array:\n', media_coluna)


# g) o desvio padrão de todos elementos do array

desvio = np.std(array)
print('Desvio padrão de todos elementos do array:\n', desvio)


# h) o desvio padrão das linhas do array

desvio_linha = np.std(array, axis=1, keepdims=True)
print('Desvio padrão das linhas do array:\n', desvio_linha)


# i) o desvio padrão dos elementos das colunas do array

desvio_coluna = np.std(array, axis=0, keepdims=True)
print('Desvio padrão das colunas do array:\n', desvio_coluna)



Array:
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
Soma dos elementos das linhas do array:
 [[15.]
 [40.]]
Multiplicação dos elementos das colunas do array:
 [[ 6. 14. 24. 36. 50.]]
Média de todos elementos do array:
 5.5
Média dos elementos das linhas do array:
 [[3.]
 [8.]]
Média dos elementos das colunas do array:
 [[3.5 4.5 5.5 6.5 7.5]]
Desvio padrão de todos elementos do array:
 2.8722813232690143
Desvio padrão das linhas do array:
 [[1.41421356]
 [1.41421356]]
Desvio padrão das colunas do array:
 [[2.5 2.5 2.5 2.5 2.5]]


Uma operação muito comum em diversos contextos consiste em encontrar a transposta de uma matriz, que nada mais é que girar a matriz no eixo diagonal principal.

Para realizar isso no numpy, basta utilizar o atributo **T** do array, conforme exemplo abaixo:

In [0]:
# numpy código 12

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print("matriz a:")
print(a)
print("matriz a transposta:")
print(a.T)

A função abaixo, fornecida pelo Numpy, permite a leitura de arquivos com dados (todos do mesmo tipo) para um array.

In [0]:
# numpy código 13

import numpy as np

arr = np.loadtxt('dados.csv',delimiter=',',dtype=np.float64)

print(arr)
print(np.average(arr,axis=1))
print (np.std(arr, axis=1))



# 3. Matplotlib
---------------

O [Matplotlib](http://matplotlib.org/) é uma biblioteca para produção de gráficos.
Nesta seção, faremos uma breve introdução ao módulo **matplotlib.pyplot**.

**3.1 Plotando Gráficos de Funções**

Uma das funções mais importantes do matplotlib é a **plot**, que permite plotar dados 2D. Observe o exemplo abaixo.

**GRÁFICO 1**


In [0]:
# **GRÁFICO 1**

import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline
# o comando acima faz com que os gráficos gerados pelo matplotlib 
# sejam mostrados nesta página e não em uma janela separada

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.2)
print("x é um array do numpy gerado com a função \"np.arange(0, 3 * np.pi, 0.2)\"")
print(x)
y = np.sin(x)
print("y também é um array do numpy calculado a partir de x - \"y = np.sin(x)\"")
print(y)
      
# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.



Com poucos ajustes é possível traçar múltiplas linhas de uma vez e adicionar um título, legendas e rótulos das coordenadas.

**GRÁFICO 2**

In [0]:
# **GRÁFICO 2**

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# computando coordenadas x e y
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)
y_001x2 = 0.01 * x**2

# Plota os pontos usando matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.plot(x, y_001x2)
plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('Seno, cosseno e 0.01x²')
plt.legend(['Seno', 'Cosseno', '0.01x²'])

# os 2 comandos abaixo ajustam o tamanho do gráfico exibido
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 6)

plt.show()



**3.2 Gráficos de barras**

O exemplo a seguir, ilustra de forma básica os gráficos de barras verticais.

**GRÁFICO 3**

In [0]:
# **GRÁFICO 3**

import matplotlib.pyplot as plt

data = [5., 25., 50., 20.]


print("barras verticais")
plt.bar(range(len(data)), data)
plt.show()


Ou horizontais.

**GRÁFICO 4**

In [0]:
# **GRÁFICO 4**

import matplotlib.pyplot as plt

data = [5., 25., 50., 20.]

print("barras horizontais")
plt.barh(range(len(data)), data, color='r')
plt.show()

Neste último gráfico alteramos a cor das barras. Usamor o 'r', que é a cor vermelha.

O matplotlib possui algumas cores predefinidas:
* 'b': blue.
* 'g': green.
* 'r': red.
* 'c': cyan.
* 'm': magenta.
* 'y': yellow.
* 'k': black.
* 'w': white.

Você também pode usar uma cor específica utilizando a combinação de vermelho, verde e azul ('#xxyyzz').

Os valores xx, yy e zz são a intensidade do vermelho, verde e azul, e podem variar de 00 a FF (código hexadecimal -cada dígito pode ter valor 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F).

O laranja, por exemplo, é '#FF7F50'.<br>
Alguns tons de cinza: [escuro - '#555555'] ; [médio - '#7F7F7F'] ; [claro - '#B0B0B0']

Na célula abaixo, teste algumas cores.

**GRÁFICO 5**


In [0]:
# **GRÁFICO 5**

import matplotlib.pyplot as plt

data = [5., 25., 50., 20.]

print("barras horizontais")
plt.barh(range(len(data)), data, color='#FF7F50')
plt.show()

Com poucas alterações, é possível imprimir um gráfico de múltiplas barras, com legenda, título, cores, etc.

Observe que **cada cor de barra é uma linha do array *dados*** 

**GRÁFICO 6**

In [0]:
# **GRÁFICO 6**

import numpy as np
import matplotlib
import matplotlib.pyplot as plt


colunas = ['2013', '2014', '2015', '2016']

dados = np.array([[5., 7., 9., 8.],
  [14., 20., 23., 27.],
  [25., 22., 15., 12.]], dtype=np.float64)

X = np.arange(4)

# plt.bar( coordenada X, coordenada Y, cor, comprimento da barra)
plt.bar(X + 0.00, dados[0], color = 'b', width = 0.267)
plt.bar(X + 0.267, dados[1], color = 'g', width = 0.267)
plt.bar(X + 0.533, dados[2], color = '#FF7F50', width = 0.267)

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de multiplas barras')
plt.legend(['Legenda 1', 'Legenda 2', 'Legenda 3'])
plt.xticks(np.arange(0, 4)+0.25, colunas)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(12, 6)

plt.show()


O código abaixo exibe o mesmo conteúdo do **GRÁFICO 6**, mas no entanto imprime as barras dentro de um loop *for*.

Observe atentamente as alterações.

**GRÁFICO 7**

In [0]:
# **GRÁFICO 7**

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

colunas = ['2013', '2014', '2015', '2016']

dados = np.array([[5., 7., 9., 8.],
  [14., 20., 23., 27.],
  [25., 22., 15., 12.]], dtype=np.float64)

# alteração 1 - X depende do número de colunas de dados
# então, em vez de colocar uma constante 4, usamos dados.shape[1]
X = np.arange(dados.shape[1])

# alteração 2 - podemos colocar as cores em uma lista
cores = ['b', 'g', '#FF7F50']

# alteração 3 - o número de barras corresponde ao número de linhas do array dados
# assim, as barras podem ser impressas em um for (usando dados.shape[0])
# no gráfico atual, escolhemos o width=0.267 porque existem 3 barras, assim as
# 3 barras ocupam 80% do espaço e os outros 20% ficam livres separando um conjunto
# de barras do outro. Essa divisão pode ser feita automaticamente
compr = 0.8/(dados.shape[0])
for i in range(0, dados.shape[0]):
    plt.bar(X + compr*i, dados[i], color = cores[i], width = compr)

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de multiplas barras')
plt.legend(['Legenda 1', 'Legenda 2', 'Legenda 3'])
# alteração 4 - legenda dos grupos de barras depende no número de colunas
plt.xticks(np.arange(0, len(colunas))+0.25, colunas)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(12, 6)

plt.show()

**Exercício 5**

Altere o código abaixo para incluir o ano de 2017: 
    * alterar colunas
    * alterar dados: (incluir valores de 2017 na última coluna de cada linha)
    
Crie também mais uma barra, de cor vermelha 'r':
    * altere *dados*: incluir mais uma linha
    * altere *cores*
    * e altere a legenda: incluindo 'Nova legenda'


In [0]:
# Exercício 5 - altere o código abaixo conforme instruções

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# >>>> inclua nova coluna
colunas = ['2013', '2014', '2015', '2016']

# >>>> altere dados
dados = np.array([[5., 7., 9., 8.],
  [14., 20., 23., 27.],
  [25., 22., 15., 12.]], dtype=np.float64)

X = np.arange(dados.shape[1])

# >>>> inclua nova cor
cores = ['b', 'g', '#FF7F50']

compr = 0.8/(dados.shape[0])
for i in range(0, dados.shape[0]):
    plt.bar(X + compr*i, dados[i], color = cores[i], width = compr)

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de multiplas barras')
# >>>> inclua nova legenda
plt.legend(['Legenda 1', 'Legenda 2', 'Legenda 3'])
plt.xticks(np.arange(0, len(colunas))+0.25, colunas)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(12, 6)

plt.show()

Uma outra forma de representar os dados do GRÁFICO 7 exibido acima é com pontos.

**Observe** o resultado da instrução *plt.ylim((0, 50))*.

Neste exemplo utilizamos estilos de linhas diferentes (para fins didáticos). A depender da situação você pode escolher não usar linhas (basta remover o parâmetro linestyle ou usar todas linhas do mesmo tipo,

Utilizamos 3 marcadores diferentes. Uma lista de marcadores está disponível na documentação do matplotlib: [clique aqui para verificar](https://matplotlib.org/api/markers_api.html)

Alguns valores comuns são:<br>
"o"	circle<br>
"v"	triangle_down<br>
"^"	triangle_up<br>
"<"	triangle_left<br>
"s"	square<br>
"p"	pentagon<br>
"P"	plus (filled)<br>
"\*"	star<br>
"h"	hexagon1<br>
"H"	hexagon2<br>
"+"	plus<br>
"x"	x<br>
"X"	x (filled)<br>
"D"	diamond<br>
"d"	thin_diamond<br>

**GRÁFICO 8**

In [0]:
# **GRÁFICO 8**

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

colunas = ['2013', '2014', '2015', '2016']

dados = np.array([[5., 7., 9., 8.],
  [14., 20., 23., 27.],
  [25., 22., 15., 12.]], dtype=np.float64)

X = np.arange(dados.shape[1])

cores = ['b', 'g', '#FF7F50']

# precisamos especificar os marcadores e as linhas de cada linha de dados
marcadores = ['s', 'o', 'v']
linhas = ['--', ':', '-.']
for i in range(0, dados.shape[0]):
    plt.plot(X, dados[i], marker=marcadores[i], linestyle=linhas[i], color=cores[i])

# função ylim
plt.ylim((0, 50))

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de pontos')
plt.legend(['Legenda 1', 'Legenda 2', 'Legenda 3'])

# mudamos a posição do xtick para coincidir com o ponto
plt.xticks(np.arange(0, len(colunas)), colunas)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(12, 6)

plt.show()

Também é possível desenhar gráficos de barras empilhadas (*stacked bar charts*).

**GRÁFICO 9**

In [0]:
# **GRÁFICO 9**

import matplotlib.pyplot as plt
import matplotlib

A = [5., 30., 45., 17.]
B = [5., 25., 50., 55.]

X = range(4)

plt.bar(X, A, color = 'b')
plt.bar(X, B, color = 'y', bottom = A)

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de barras empilhadas')
plt.legend(['Azul', 'Amarelo'])

# os 2 comandos abaixo ajustam o tamanho do gráfico exibido
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 6)

plt.show()

O exemplo abaixo possui 3 barras empilhadas.

**GRÁFICO 10**

In [0]:
# **GRÁFICO 10** 

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

# Dados armazenados num array do numpy
data = np.array([[5., 30., 45., 22.],
                 [5., 25., 50., 20.],
                 [61.,  12.,  1.,  1.]])

# lista de cores
color_list = ['b', 'g', 'y']

X = np.arange(data.shape[1]) # equivale a X = np.array([0, 1, 2, 3])

# o for plota as 3 barras 
for i in range(data.shape[0]):
  plt.bar(X, data[i],
    bottom = np.sum(data[:i], axis = 0),
    color = color_list[i % len(color_list)])

plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de barras empilhadas')
plt.legend(['Azul', 'Verde', 'Amarelo'])

# os 2 comandos abaixo ajustam o tamanho do gráfico exibido
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 8)

plt.show()

No exemplo abaixo, usamos o numpy para ler os resultados de um experimento usando 5 métodos distintos.

O arquivo dados.csv contém resultados de 5 métodos testados em um experimento (um em cada linha).<br>
Cada linha do arquivo dados.csv contém 11 resultados de um método testado. Os valores estão separados por vírgula.<br>

88.5,88.4,88.4,88.5,89.0,86.4,88.4,89.1,88.9,86.4,87.2<br>
85.7,85.7,85.7,85.7,85.7,85.7,85.7,85.7,85.7,85.7,85.7<br>
84.5,88.9,88.9,86.2,86.8,85.3,87.9,87.3,88.9,84.6,87.2<br>
86.5,85.4,87.6,84.9,87.3,88.5,86.7,85.4,85.8,88.3,87.2<br>
87.5,89.4,86.5,82.4,89.1,86.8,87.4,88.5,88.9,88.9,87.2<br>

**GRÁFICO 11**

In [0]:
# **GRÁFICO 11**

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

arr = np.loadtxt('dados.csv',delimiter=',',dtype=np.float64)

X = np.arange(5)

cores = ['r', 'g', 'b', 'y', 'c']

for i in range(0, 5):
    # plt.bar( coordenada X, coordenada Y, cor, comprimento da barra)
    plt.bar(X[i] + 0.2, np.average( arr[i,:] ), color=cores[i], width = 0.6)
    
plt.ylim((0,119))
plt.xlim=((0,7))
plt.xlabel('rótulo do eixo x')
plt.ylabel('rótulo do eixo y')
plt.title('gráfico de barras')
plt.legend(['Método 1', 'Método 2', 'Método 3', 'Método 4', 'Método 5'])


# os 2 comandos abaixo ajustam o tamanho do gráfico exibido
fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 6)

plt.show()


O numpy fornece uma função para plotar histogramas. 

O parêmetro bins indica o número de divisões dos valores fornecidos para a função.

A função hist recebe como entrada uma lista de valores e **a faixa** dos valores é dividida igualmente pelo número de bins informado. 

O gráfico gerado terá uma barra para cada bin. A altura de cada barra é o número de valores correspondente a cada bin.

**GRÁFICO 12**

In [0]:
# **GRÁFICO 12**

import numpy as np
import matplotlib.pyplot as plt

# observe que o não existe nenhum valor 5.
# os valores não precisariam estar ordenados - na lista abaixo isso
# é feito apenas para fins didáticos
X = np.array([0., 0., 1., 1., 1., 2., 2., 3.,
              4., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
              8., 8., 8., 9.])

plt.hist(X, bins = 10)

plt.show()


Se informássemos o número de bins igual a 5, a função automaticamente agregaria os valores
0-1, 2-3, 4-5, 6-7, 8-9

**GRÁFICO 13**

In [0]:
# **GRÁFICO 13**

import numpy as np
import matplotlib.pyplot as plt

X = np.array([0., 0., 1., 1., 1., 2., 2., 3.,
              4., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
              8., 8., 8., 9.])

# a única mudança desse gráfico em relação ao 12 é que informamos o número de bins igual a 5
plt.hist(X, bins = 5)

plt.show()

Por fim, vamos exemplificar um gráfico de dispersão (*scatterplot*) simples.

**GRÁFICO 14**


In [0]:
# ** GRÁFICO 14 **

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

num_points = 100
gradient = 0.5
x = np.array(range(num_points))
# dados gerados aleatoriamente, para exemplificar
y = np.random.randn(num_points) * 10 + x*gradient

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 6)
plt.title('Um gráfico de dispersão simples')

sc =plt.scatter(x, y)

plt.show()

As cores e o tamanho dos pontos podem ser customizados.

Você pode escolher um mapa de cor com a instução:
```python
plt.rcParams['image.cmap'] = 'viridis'
```

Existem diversos mapas de cores diponíveis: 'viridis', 'plasma', 'inferno', 'magma', 'gray', dentre outros.

** GRÁFICO 15 **

In [0]:
# ** GRÁFICO 15 **

import numpy as np
import matplotlib
import matplotlib.pyplot as plt

num_points = 100
gradient = 0.5
x = np.array(range(num_points))
# dados gerados aleatoriamente, para exemplificar
y = np.random.randn(num_points) * 10 + x*gradient

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10, 6)
plt.title('Um gráfico de dispersão com cores e tamanho variados')

# escolhe o mapa de cores 'viridis'
plt.rcParams['image.cmap'] = 'viridis'

# cores geradas aleatoriamente: função produz 100 cores randômicas do mapa de cores padrão
colors = np.random.rand(num_points)

# definimos o tamanho dos marcadores: (2 + pontos*8)²
size = (2 + np.random.rand(num_points) * 8) ** 2

sc =plt.scatter(x, y, s=size, c=colors, alpha=0.5)

plt.show()

# Aproveitem o conhecimento !